x-spark-common: &spark-common
  build: . 
  volumes:
    - ./jobs:/opt/spark/jobs
    - ./inputs:/opt/spark/input
    - spark-ivy-cache:/home/spark/.ivy2 
  command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  depends_on:
    - spark-master
  environment:
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 1g
    PYTHONPATH: /opt/spark/jobs
  networks:
    - datamasterylab

services:
  spark-master:
    build: . 
    volumes:
      - ./jobs:/opt/spark/jobs
      - ./inputs:/opt/spark/input
      - spark-ivy-cache:/home/spark/.ivy2  
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      PYTHONPATH: /opt/spark/jobs
    ports:
      - "9090:8080"
      - "7077:7077"
    networks:
      - datamasterylab
    
  spark-worker-1:
    <<: *spark-common
    
  spark-worker-2:
    <<: *spark-common

networks:
  datamasterylab:
    driver: bridge

volumes:
  spark-ivy-cache:  